# ============================================================
# RETAIL ANALYTICS
# MODEL COMPARATIVE ANALYSIS
# ============================================================
#
# Purpose:
# This script creates a presentation-ready comparative analysis
# of all ML, DL and Hybrid models used in the Retail Analytics
# project.
#
# Models compared:
#   1. Linear Regression
#   2. Decision Tree
#   3. Random Forest
#   4. XGBoost
#   5. LSTM
#   6. GRU
#   7. XGBoost + LSTM Feature Hybrid  <-- PROPOSED MODEL
#   8. LSTM + Random Forest
#   9. GRU + XGBoost
#  10. GRU + Random Forest
#
# Metrics:
#   - R2
#   - MAE
#   - RMSE
#   - MAPE
#
# Input:
#   outputs/05_Machine_Learning/06_Model_Comparison/
#
# Output:
#   outputs/11_Model_Comparison/
#
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle


# ============================================================
# 2. PROJECT PATHS
# ============================================================

# Find the project root directory.
BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)


# ------------------------------------------------------------
# Original ML results folder
# ------------------------------------------------------------
#
# machine_learning.py creates the original model comparison
# results here.
#
# ------------------------------------------------------------

ML_COMPARISON_DIR = os.path.join(
    BASE_DIR,
    "outputs",
    "05_Machine_Learning",
    "06_Model_Comparison"
)


# ------------------------------------------------------------
# Final comparative-analysis output folder
# ------------------------------------------------------------
#
# This is the new dedicated folder for Review-3 comparison
# charts, Excel files and summary files.
#
# ------------------------------------------------------------

COMPARISON_DIR = os.path.join(
    BASE_DIR,
    "outputs",
    "11_Model_Comparison"
)


# Create the output folder if it does not exist.

os.makedirs(
    COMPARISON_DIR,
    exist_ok=True
)


# ============================================================
# 3. INPUT FILE
# ============================================================
#
# IMPORTANT:
# The input is the comparison Excel generated by
# machine_learning.py.
#
# The comparative_analysis.py script does NOT retrain models.
#
# ============================================================

comparison_file = os.path.join(
    ML_COMPARISON_DIR,
    "Model_Comparison_All_Metrics.xlsx"
)


if not os.path.exists(comparison_file):

    raise FileNotFoundError(

        "\n"
        "============================================================\n"
        "MODEL COMPARISON INPUT FILE NOT FOUND\n"
        "============================================================\n\n"

        f"Expected file:\n{comparison_file}\n\n"

        "Please run machine_learning.py first and make sure the "
        "Model_Comparison_All_Metrics.xlsx file exists inside:\n"

        f"{ML_COMPARISON_DIR}\n"

    )


# ============================================================
# 4. LOAD MODEL COMPARISON RESULTS
# ============================================================

comparison = pd.read_excel(
    comparison_file
)


print("=" * 80)
print("RETAIL ANALYTICS")
print("MODEL COMPARATIVE ANALYSIS")
print("=" * 80)

print(
    f"\nInput file loaded successfully:"
)

print(
    comparison_file
)

print(
    f"\nTotal rows loaded: {len(comparison)}"
)


# ============================================================
# 5. REQUIRED COLUMNS
# ============================================================

required_columns = [

    "Model",
    "Model Type",
    "Evaluation Level",
    "Test Period",
    "MAE",
    "MSE",
    "RMSE",
    "R2",
    "MAPE",
    "SMAPE"

]


missing_columns = [

    column
    for column in required_columns
    if column not in comparison.columns

]


if missing_columns:

    raise ValueError(

        "\nThe following required columns are missing "
        "from the ML comparison Excel file:\n"

        + str(missing_columns)

    )


# ============================================================
# 6. CONVERT METRICS TO NUMERIC
# ============================================================

metric_columns = [

    "MAE",
    "MSE",
    "RMSE",
    "R2",
    "MAPE",
    "SMAPE"

]


for column in metric_columns:

    comparison[column] = pd.to_numeric(

        comparison[column],

        errors="coerce"

    )


# ============================================================
# 7. DEFINE MODEL ORDER
# ============================================================
#
# Fixed order is used so the graph is consistent and easy to
# explain during the Review-3 presentation.
#
# ============================================================

model_order = [

    "Linear Regression",

    "Decision Tree",

    "Random Forest",

    "XGBoost",

    "LSTM",

    "GRU",

    "XGBoost + LSTM Feature Hybrid",

    "LSTM + Random Forest",

    "GRU + XGBoost",

    "GRU + Random Forest"

]


# ============================================================
# 8. CHECK AVAILABLE MODELS
# ============================================================

available_models = [

    model

    for model in model_order

    if model in comparison["Model"].astype(str).values

]


missing_models = [

    model

    for model in model_order

    if model not in comparison["Model"].astype(str).values

]


if missing_models:

    print(
        "\nWARNING:"
    )

    print(
        "The following expected models were not found:"
    )

    for model in missing_models:

        print(
            f" - {model}"
        )


# Keep only the models expected for this analysis.

comparison = comparison[

    comparison["Model"].astype(str).isin(
        available_models
    )

].copy()


# ============================================================
# 9. SORT MODELS IN FIXED ORDER
# ============================================================

comparison["Model"] = pd.Categorical(

    comparison["Model"].astype(str),

    categories=available_models,

    ordered=True

)


comparison = comparison.sort_values(

    "Model"

).reset_index(

    drop=True

)


# ============================================================
# 10. PRINT MODEL PERFORMANCE
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "MODEL PERFORMANCE"
)

print(
    "=" * 80
)


display_columns = [

    "Model",
    "Model Type",
    "Evaluation Level",
    "R2",
    "MAE",
    "RMSE",
    "MAPE"

]


print(

    comparison[
        display_columns
    ].to_string(
        index=False
    )

)


# ============================================================
# 11. IDENTIFY PROPOSED MODEL
# ============================================================

PROPOSED_MODEL = (
    "XGBoost + LSTM Feature Hybrid"
)


if PROPOSED_MODEL not in comparison["Model"].astype(str).values:

    raise ValueError(

        "\nProposed model was not found.\n\n"

        f"Expected:\n{PROPOSED_MODEL}\n\n"

        "Check the model name in Model_Comparison_All_Metrics.xlsx."

    )


# ============================================================
# 12. SAVE CLEAN COMPARISON TABLE
# ============================================================

clean_comparison = comparison[
    display_columns
].copy()


clean_comparison[

    [
        "R2",
        "MAE",
        "RMSE",
        "MAPE"
    ]

] = clean_comparison[

    [
        "R2",
        "MAE",
        "RMSE",
        "MAPE"
    ]

].round(4)


clean_table_path = os.path.join(

    COMPARISON_DIR,

    "Comparative_Analysis_Table.xlsx"

)


clean_comparison.to_excel(

    clean_table_path,

    index=False

)


# ============================================================
# 13. SHORT MODEL NAMES FOR GRAPHS
# ============================================================

models = (

    comparison[
        "Model"
    ]
    .astype(str)
    .tolist()

)


short_names = {

    "Linear Regression":
        "Linear\nRegression",

    "Decision Tree":
        "Decision\nTree",

    "Random Forest":
        "Random\nForest",

    "XGBoost":
        "XGBoost",

    "LSTM":
        "LSTM",

    "GRU":
        "GRU",

    "XGBoost + LSTM Feature Hybrid":
        "XGB + LSTM\n(Proposed)",

    "LSTM + Random Forest":
        "LSTM + RF",

    "GRU + XGBoost":
        "GRU + XGB",

    "GRU + Random Forest":
        "GRU + RF"

}


labels = [

    short_names.get(
        model,
        model
    )

    for model in models

]


# ============================================================
# 14. MAIN COMPARATIVE ANALYSIS FUNCTION
# ============================================================

def plot_metric(

    ax,
    metric,
    title,
    ylabel

):

    """
    Creates one metric comparison chart.

    The proposed model is highlighted with a dashed box.
    """

    values = (

        comparison[
            metric
        ]
        .astype(float)
        .values

    )


    x = np.arange(
        len(models)
    )


    # --------------------------------------------------------
    # Create bars
    # --------------------------------------------------------

    bars = ax.bar(

        x,

        values

    )


    # --------------------------------------------------------
    # Find proposed model
    # --------------------------------------------------------

    proposed_index = models.index(

        PROPOSED_MODEL

    )


    # --------------------------------------------------------
    # Highlight proposed model bar
    # --------------------------------------------------------

    bars[
        proposed_index
    ].set_linewidth(3)


    # --------------------------------------------------------
    # Calculate chart maximum
    # --------------------------------------------------------

    max_value = np.nanmax(
        values
    )


    if max_value <= 0:

        max_value = 1


    # --------------------------------------------------------
    # Dashed box around proposed model
    # --------------------------------------------------------

    rectangle_height = (
        max_value * 1.12
    )


    rectangle = Rectangle(

        (
            proposed_index - 0.45,
            0
        ),

        0.90,

        rectangle_height,

        fill=False,

        linestyle="--",

        linewidth=2.5

    )


    ax.add_patch(
        rectangle
    )


    # --------------------------------------------------------
    # Value labels
    # --------------------------------------------------------

    for i, value in enumerate(values):

        if np.isnan(value):

            continue


        if metric == "R2":

            text = f"{value:.3f}"

        else:

            text = f"{value:.2f}"


        ax.text(

            i,

            value,

            text,

            ha="center",

            va="bottom",

            fontsize=9,

            fontweight="bold"

        )


    # --------------------------------------------------------
    # Formatting
    # --------------------------------------------------------

    ax.set_title(

        title,

        fontsize=15,

        fontweight="bold"

    )


    ax.set_ylabel(

        ylabel,

        fontsize=11

    )


    ax.set_xticks(
        x
    )


    ax.set_xticklabels(

        labels,

        fontsize=9

    )


    ax.grid(

        axis="y",

        linestyle="--",

        alpha=0.30

    )


    ax.set_ylim(

        0,

        max_value * 1.20

    )


# ============================================================
# 15. CREATE MAIN COMPARATIVE ANALYSIS FIGURE
# ============================================================
#
# Four metrics are displayed as four panels:
#
#   R²
#   MAE
#   RMSE
#   MAPE
#
# This is preferable to putting metrics with different units
# on one common y-axis.
#
# ============================================================

fig, axes = plt.subplots(

    2,

    2,

    figsize=(18, 11)

)


fig.suptitle(

    "Sales Forecasting Model Comparative Analysis",

    fontsize=22,

    fontweight="bold",

    y=0.98

)


# ------------------------------------------------------------
# R²
# ------------------------------------------------------------

plot_metric(

    axes[0, 0],

    "R2",

    "R² Score",

    "R² Score"

)


# ------------------------------------------------------------
# MAE
# ------------------------------------------------------------

plot_metric(

    axes[0, 1],

    "MAE",

    "Mean Absolute Error",

    "MAE"

)


# ------------------------------------------------------------
# RMSE
# ------------------------------------------------------------

plot_metric(

    axes[1, 0],

    "RMSE",

    "Root Mean Squared Error",

    "RMSE"

)


# ------------------------------------------------------------
# MAPE
# ------------------------------------------------------------

plot_metric(

    axes[1, 1],

    "MAPE",

    "Mean Absolute Percentage Error",

    "MAPE (%)"

)


# ============================================================
# 16. ADD PROPOSED MODEL NOTE
# ============================================================

fig.text(

    0.5,

    0.015,

    "Dashed box = Proposed Model: "
    "XGBoost + LSTM Feature Hybrid",

    ha="center",

    fontsize=13,

    fontweight="bold"

)


plt.tight_layout(

    rect=[
        0,
        0.04,
        1,
        0.95
    ]

)


# ============================================================
# 17. SAVE MAIN COMPARATIVE ANALYSIS
# ============================================================

main_figure_path = os.path.join(

    COMPARISON_DIR,

    "Sales_Forecasting_Model_Comparative_Analysis.png"

)


plt.savefig(

    main_figure_path,

    dpi=300,

    bbox_inches="tight"

)


plt.close()


# ============================================================
# 18. HYBRID MODEL COMPARISON
# ============================================================
#
# We explicitly identify the four hybrid models instead of
# relying on the exact wording of the "Model Type" column.
#
# ============================================================

hybrid_model_names = [

    "XGBoost + LSTM Feature Hybrid",

    "LSTM + Random Forest",

    "GRU + XGBoost",

    "GRU + Random Forest"

]


hybrid_models = comparison[

    comparison[
        "Model"
    ]
    .astype(str)
    .isin(
        hybrid_model_names
    )

].copy()


# Sort hybrids in the desired order.

hybrid_models["Hybrid_Order"] = (

    hybrid_models[
        "Model"
    ]
    .astype(str)
    .map(

        {
            model: i
            for i, model
            in enumerate(
                hybrid_model_names
            )
        }

    )

)


hybrid_models = hybrid_models.sort_values(

    "Hybrid_Order"

).reset_index(

    drop=True

)


# ============================================================
# 19. CREATE HYBRID COMPARISON FIGURE
# ============================================================

if not hybrid_models.empty:

    hybrid_names = (

        hybrid_models[
            "Model"
        ]
        .astype(str)
        .tolist()

    )


    hybrid_labels = [

        short_names.get(
            model,
            model
        )

        for model in hybrid_names

    ]


    fig, axes = plt.subplots(

        1,

        3,

        figsize=(18, 6)

    )


    fig.suptitle(

        "Hybrid Model Comparative Analysis",

        fontsize=21,

        fontweight="bold",

        y=1.02

    )


    hybrid_metrics = [

        (
            "R2",
            "R² Score"
        ),

        (
            "MAE",
            "MAE"
        ),

        (
            "RMSE",
            "RMSE"
        )

    ]


    for ax, (
        metric,
        title
    ) in zip(

        axes,

        hybrid_metrics

    ):

        values = (

            hybrid_models[
                metric
            ]
            .astype(float)
            .values

        )


        x = np.arange(

            len(
                hybrid_names
            )

        )


        bars = ax.bar(

            x,

            values

        )


        # ----------------------------------------------------
        # Highlight proposed model
        # ----------------------------------------------------

        if PROPOSED_MODEL in hybrid_names:

            proposed_index = hybrid_names.index(

                PROPOSED_MODEL

            )


            bars[
                proposed_index
            ].set_linewidth(3)


            max_value = np.nanmax(
                values
            )


            if max_value <= 0:

                max_value = 1


            rectangle = Rectangle(

                (
                    proposed_index - 0.45,
                    0
                ),

                0.90,

                max_value * 1.10,

                fill=False,

                linestyle="--",

                linewidth=2.5

            )


            ax.add_patch(
                rectangle
            )


        # ----------------------------------------------------
        # Add values
        # ----------------------------------------------------

        for i, value in enumerate(values):

            if np.isnan(value):

                continue


            if metric == "R2":

                text = f"{value:.3f}"

            else:

                text = f"{value:.2f}"


            ax.text(

                i,

                value,

                text,

                ha="center",

                va="bottom",

                fontsize=10,

                fontweight="bold"

            )


        # ----------------------------------------------------
        # Formatting
        # ----------------------------------------------------

        ax.set_title(

            title,

            fontsize=15,

            fontweight="bold"

        )


        ax.set_xticks(
            x
        )


        ax.set_xticklabels(

            hybrid_labels,

            rotation=20,

            ha="right"

        )


        ax.grid(

            axis="y",

            linestyle="--",

            alpha=0.30

        )


        max_value = np.nanmax(
            values
        )


        if max_value <= 0:

            max_value = 1


        ax.set_ylim(

            0,

            max_value * 1.20

        )


    fig.text(

        0.5,

        -0.02,

        "Dashed box = Proposed Model: "
        "XGBoost + LSTM Feature Hybrid",

        ha="center",

        fontsize=12,

        fontweight="bold"

    )


    plt.tight_layout()


    hybrid_figure_path = os.path.join(

        COMPARISON_DIR,

        "Hybrid_Model_Comparative_Analysis.png"

    )


    plt.savefig(

        hybrid_figure_path,

        dpi=300,

        bbox_inches="tight"

    )


    plt.close()


else:

    print(

        "\nWARNING: No hybrid models were found. "
        "Hybrid comparison figure was not created."

    )


# ============================================================
# 20. PROPOSED MODEL VS XGBOOST
# ============================================================

xgb_match = comparison[

    comparison[
        "Model"
    ].astype(str)
    == "XGBoost"

]


proposed_match = comparison[

    comparison[
        "Model"
    ].astype(str)
    == PROPOSED_MODEL

]


if xgb_match.empty:

    raise ValueError(
        "XGBoost model was not found."
    )


if proposed_match.empty:

    raise ValueError(
        "Proposed model was not found."
    )


xgb_row = xgb_match.iloc[0]

proposed_row = proposed_match.iloc[0]


# ============================================================
# 21. CALCULATE PROPOSED MODEL CHANGES
# ============================================================

# Positive improvement means the error metric decreased.

mae_improvement = (

    (
        xgb_row["MAE"]
        -
        proposed_row["MAE"]
    )

    /

    xgb_row["MAE"]

    *

    100

)


rmse_improvement = (

    (
        xgb_row["RMSE"]
        -
        proposed_row["RMSE"]
    )

    /

    xgb_row["RMSE"]

    *

    100

)


mape_improvement = (

    (
        xgb_row["MAPE"]
        -
        proposed_row["MAPE"]
    )

    /

    xgb_row["MAPE"]

    *

    100

)


r2_change = (

    proposed_row["R2"]
    -
    xgb_row["R2"]

)


# ============================================================
# 22. PROPOSED MODEL VS XGBOOST TABLE
# ============================================================

proposed_comparison = pd.DataFrame({

    "Metric": [

        "R²",
        "MAE",
        "RMSE",
        "MAPE"

    ],

    "XGBoost": [

        xgb_row["R2"],
        xgb_row["MAE"],
        xgb_row["RMSE"],
        xgb_row["MAPE"]

    ],

    "Proposed XGBoost + LSTM": [

        proposed_row["R2"],
        proposed_row["MAE"],
        proposed_row["RMSE"],
        proposed_row["MAPE"]

    ],

    "Change": [

        r2_change,

        proposed_row["MAE"]
        -
        xgb_row["MAE"],

        proposed_row["RMSE"]
        -
        xgb_row["RMSE"],

        proposed_row["MAPE"]
        -
        xgb_row["MAPE"]

    ]

})


proposed_comparison = (

    proposed_comparison.round(4)

)


proposed_comparison_path = os.path.join(

    COMPARISON_DIR,

    "Proposed_Model_vs_XGBoost.xlsx"

)


proposed_comparison.to_excel(

    proposed_comparison_path,

    index=False

)


# ============================================================
# 23. HYBRID IMPROVEMENT ANALYSIS
# ============================================================

hybrid_pairs = [

    (
        "XGBoost + LSTM Feature Hybrid",
        "XGBoost"
    ),

    (
        "GRU + XGBoost",
        "XGBoost"
    ),

    (
        "LSTM + Random Forest",
        "Random Forest"
    ),

    (
        "GRU + Random Forest",
        "Random Forest"
    )

]


improvement_rows = []


for hybrid_name, baseline_name in hybrid_pairs:

    hybrid_match = comparison[

        comparison[
            "Model"
        ].astype(str)
        == hybrid_name

    ]


    baseline_match = comparison[

        comparison[
            "Model"
        ].astype(str)
        == baseline_name

    ]


    if hybrid_match.empty:

        continue


    if baseline_match.empty:

        continue


    hybrid = hybrid_match.iloc[0]

    baseline = baseline_match.iloc[0]


    # --------------------------------------------------------
    # MAE improvement
    # --------------------------------------------------------

    mae_improvement_value = (

        (
            baseline["MAE"]
            -
            hybrid["MAE"]
        )

        /

        baseline["MAE"]

        *

        100

    )


    # --------------------------------------------------------
    # RMSE improvement
    # --------------------------------------------------------

    rmse_improvement_value = (

        (
            baseline["RMSE"]
            -
            hybrid["RMSE"]
        )

        /

        baseline["RMSE"]

        *

        100

    )


    # --------------------------------------------------------
    # MAPE improvement
    # --------------------------------------------------------

    mape_improvement_value = (

        (
            baseline["MAPE"]
            -
            hybrid["MAPE"]
        )

        /

        baseline["MAPE"]

        *

        100

    )


    # --------------------------------------------------------
    # R² change
    # --------------------------------------------------------

    r2_change_value = (

        hybrid["R2"]
        -
        baseline["R2"]

    )


    improvement_rows.append({

        "Hybrid Model":
            hybrid_name,

        "Baseline Model":
            baseline_name,

        "Baseline R2":
            baseline["R2"],

        "Hybrid R2":
            hybrid["R2"],

        "R2 Change":
            r2_change_value,

        "Baseline MAE":
            baseline["MAE"],

        "Hybrid MAE":
            hybrid["MAE"],

        "MAE Improvement (%)":
            mae_improvement_value,

        "Baseline RMSE":
            baseline["RMSE"],

        "Hybrid RMSE":
            hybrid["RMSE"],

        "RMSE Improvement (%)":
            rmse_improvement_value,

        "Baseline MAPE":
            baseline["MAPE"],

        "Hybrid MAPE":
            hybrid["MAPE"],

        "MAPE Improvement (%)":
            mape_improvement_value

    })


improvement_df = pd.DataFrame(

    improvement_rows

)


if not improvement_df.empty:

    improvement_df = improvement_df.round(4)


    improvement_path = os.path.join(

        COMPARISON_DIR,

        "Hybrid_Improvement_Analysis.xlsx"

    )


    improvement_df.to_excel(

        improvement_path,

        index=False

    )


# ============================================================
# 24. COMPLETE COMPARISON EXCEL
# ============================================================
#
# This workbook contains:
#
#   Sheet 1 -> All Models
#   Sheet 2 -> Hybrid Models
#   Sheet 3 -> Proposed vs XGBoost
#   Sheet 4 -> Hybrid Improvements
#
# ============================================================

complete_excel_path = os.path.join(

    COMPARISON_DIR,

    "Complete_Model_Comparative_Analysis.xlsx"

)


with pd.ExcelWriter(

    complete_excel_path,

    engine="openpyxl"

) as writer:

    clean_comparison.to_excel(

        writer,

        sheet_name="All Models",

        index=False

    )


    if not hybrid_models.empty:

        hybrid_export = hybrid_models[
            display_columns
        ].copy()


        hybrid_export.to_excel(

            writer,

            sheet_name="Hybrid Models",

            index=False

        )


    proposed_comparison.to_excel(

        writer,

        sheet_name="Proposed vs XGBoost",

        index=False

    )


    if not improvement_df.empty:

        improvement_df.to_excel(

            writer,

            sheet_name="Hybrid Improvements",

            index=False

        )


# ============================================================
# 25. WRITE TEXT SUMMARY
# ============================================================

summary_file = os.path.join(

    COMPARISON_DIR,

    "Comparative_Analysis_Summary.txt"

)


with open(

    summary_file,

    "w",

    encoding="utf-8"

) as file:

    file.write(

        "============================================================\n"
        "RETAIL ANALYTICS\n"
        "MODEL COMPARATIVE ANALYSIS\n"
        "============================================================\n\n"

    )


    file.write(

        "MODELS EVALUATED\n"
        "-----------------\n"

    )


    for model in models:

        file.write(

            f"- {model}\n"

        )


    file.write("\n")


    file.write(

        "PROPOSED MODEL\n"
        "--------------\n"

    )


    file.write(

        f"{PROPOSED_MODEL}\n\n"

    )


    file.write(

        "PROPOSED MODEL PERFORMANCE\n"
        "---------------------------\n"

    )


    file.write(

        f"R2   : {proposed_row['R2']:.4f}\n"

    )


    file.write(

        f"MAE  : {proposed_row['MAE']:.4f}\n"

    )


    file.write(

        f"RMSE : {proposed_row['RMSE']:.4f}\n"

    )


    file.write(

        f"MAPE : {proposed_row['MAPE']:.4f}%\n\n"

    )


    file.write(

        "COMPARISON WITH XGBOOST\n"
        "-----------------------\n"

    )


    file.write(

        f"XGBoost R2       : "
        f"{xgb_row['R2']:.4f}\n"

    )


    file.write(

        f"Proposed R2      : "
        f"{proposed_row['R2']:.4f}\n"

    )


    file.write(

        f"R2 Change        : "
        f"{r2_change:.4f}\n\n"

    )


    file.write(

        f"MAE Improvement  : "
        f"{mae_improvement:.4f}%\n"

    )


    file.write(

        f"RMSE Improvement : "
        f"{rmse_improvement:.4f}%\n"

    )


    file.write(

        f"MAPE Improvement : "
        f"{mape_improvement:.4f}%\n\n"

    )


    file.write(

        "INTERPRETATION\n"
        "--------------\n"

    )


    file.write(

        "The comparative analysis evaluates multiple "
        "machine-learning, deep-learning and hybrid "
        "configurations using the experimental results "
        "generated during model evaluation.\n\n"

    )


    file.write(

        "The proposed model is the XGBoost + LSTM "
        "Feature Hybrid. Its performance is compared "
        "with standalone XGBoost and alternative "
        "hybrid configurations.\n\n"

    )


    file.write(

        "For regression evaluation, higher R2 indicates "
        "better explanatory performance, while lower "
        "MAE, RMSE and MAPE indicate lower prediction "
        "error.\n\n"

    )


    file.write(

        "The magnitude of improvement is reported as the "
        "observed experimental difference and should not "
        "be interpreted as a claim of a large improvement "
        "unless supported by the measured results.\n\n"

    )


    file.write(

        "IMPORTANT COMPARABILITY NOTE\n"
        "-----------------------------\n"

    )


    file.write(

        "The standalone LSTM and GRU models were evaluated "
        "at the monthly level, whereas the transaction-level "
        "ML and hybrid models use transaction-level evaluation. "
        "Therefore, their metric values should be interpreted "
        "with the evaluation level in mind.\n"

    )


# ============================================================
# 26. FINAL TERMINAL OUTPUT
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "COMPARATIVE ANALYSIS COMPLETED SUCCESSFULLY"
)

print(
    "=" * 80
)


print(
    "\nModels included:"
)

for model in models:

    print(
        f" - {model}"
    )


print(
    "\nProposed Model:"
)

print(
    PROPOSED_MODEL
)


print(
    "\nProposed Model Metrics:"
)

print(

    f"R²   = "
    f"{proposed_row['R2']:.4f}"

)


print(

    f"MAE  = "
    f"{proposed_row['MAE']:.4f}"

)


print(

    f"RMSE = "
    f"{proposed_row['RMSE']:.4f}"

)


print(

    f"MAPE = "
    f"{proposed_row['MAPE']:.4f}%"

)


print(
    "\nComparison with XGBoost:"
)


print(

    f"R² Change          = "
    f"{r2_change:.4f}"

)


print(

    f"MAE Improvement    = "
    f"{mae_improvement:.4f}%"

)


print(

    f"RMSE Improvement   = "
    f"{rmse_improvement:.4f}%"

)


print(

    f"MAPE Improvement   = "
    f"{mape_improvement:.4f}%"

)


print(
    "\nInput folder:"
)

print(
    ML_COMPARISON_DIR
)


print(
    "\nOutput folder:"
)

print(
    COMPARISON_DIR
)


print(
    "\nGenerated files:"
)

print(
    "1. Comparative_Analysis_Table.xlsx"
)

print(
    "2. Sales_Forecasting_Model_Comparative_Analysis.png"
)

print(
    "3. Hybrid_Model_Comparative_Analysis.png"
)

print(
    "4. Proposed_Model_vs_XGBoost.xlsx"
)

print(
    "5. Hybrid_Improvement_Analysis.xlsx"
)

print(
    "6. Complete_Model_Comparative_Analysis.xlsx"
)

print(
    "7. Comparative_Analysis_Summary.txt"
)


print(
    "\n" + "=" * 80
)

print(
    "DONE"
)

print(
    "=" * 80
)