# ============================================================
# RFM CUSTOMER ANALYSIS
# Retail Sales Analytics Project
# ============================================================

import os
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# BLOCK 1: Define input and output paths
# ------------------------------------------------------------
# This block tells Python where the feature-engineered data
# is located and where the RFM results should be saved.

input_file = r"outputs\03_Feature_Engineering\Feature_Engineered_Superstore.xlsx"

output_folder = r"outputs\07_Customer_Intelligence"

os.makedirs(output_folder, exist_ok=True)

output_file = os.path.join(
    output_folder,
    "RFM_Customer_Value.xlsx"
)

print("=" * 60)
print("RFM CUSTOMER ANALYSIS")
print("=" * 60)

# ------------------------------------------------------------
# BLOCK 2: Load the dataset
# ------------------------------------------------------------
# We use the feature-engineered dataset already created
# during the previous project stage.

df = pd.read_excel(input_file)

print("\nDataset loaded successfully.")
print("Rows:", len(df))
print("Columns:", len(df.columns))

# ------------------------------------------------------------
# BLOCK 3: Convert Order Date
# ------------------------------------------------------------
# Order Date is required to calculate Recency.

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

# Remove records where important customer information is missing.

df = df.dropna(
    subset=["Customer ID", "Order Date", "Sales"]
)

# ------------------------------------------------------------
# BLOCK 4: Set analysis date
# ------------------------------------------------------------
# We use the day after the latest order date as the reference date.
# Recency = number of days since the customer's latest purchase.

analysis_date = df["Order Date"].max() + pd.Timedelta(days=1)

print("\nAnalysis Date:", analysis_date.date())

# ------------------------------------------------------------
# BLOCK 5: Calculate RFM values
# ------------------------------------------------------------
# Recency:
# Number of days since the customer's most recent purchase.
#
# Frequency:
# Number of unique orders made by the customer.
#
# Monetary:
# Total sales generated by the customer.

rfm = df.groupby("Customer ID").agg(
    Recency=("Order Date",
             lambda x: (analysis_date - x.max()).days),

    Frequency=("Order ID",
               "nunique"),

    Monetary=("Sales",
              "sum")
).reset_index()

print("\nRFM values calculated.")
print("Number of customers:", len(rfm))

# ------------------------------------------------------------
# BLOCK 6: Create RFM scores
# ------------------------------------------------------------
# Customers are divided into five groups for each RFM measure.
#
# Recency:
# Lower recency is better, therefore the score is reversed.
#
# Frequency:
# Higher frequency is better.
#
# Monetary:
# Higher monetary value is better.

def create_score(series, reverse=False):

    # rank(method="first") prevents duplicate-value problems
    # when using qcut.

    ranked = series.rank(method="first")

    score = pd.qcut(
        ranked,
        q=5,
        labels=[1, 2, 3, 4, 5]
    ).astype(int)

    if reverse:
        score = 6 - score

    return score


rfm["R_Score"] = create_score(
    rfm["Recency"],
    reverse=True
)

rfm["F_Score"] = create_score(
    rfm["Frequency"],
    reverse=False
)

rfm["M_Score"] = create_score(
    rfm["Monetary"],
    reverse=False
)

# ------------------------------------------------------------
# BLOCK 7: Calculate combined RFM score
# ------------------------------------------------------------
# The overall RFM score is the sum of the three individual
# R, F and M scores.

rfm["RFM_Score"] = (
    rfm["R_Score"]
    + rfm["F_Score"]
    + rfm["M_Score"]
)

# ------------------------------------------------------------
# BLOCK 8: Assign Customer Value
# ------------------------------------------------------------
# Customers are classified into:
# High Value
# Medium Value
# Low Value
#
# The classification is based on the combined RFM score.

def customer_value(score):

    if score >= 12:
        return "High Value"

    elif score >= 8:
        return "Medium Value"

    else:
        return "Low Value"


rfm["Customer_Value"] = rfm["RFM_Score"].apply(
    customer_value
)

# ------------------------------------------------------------
# BLOCK 9: Add customer-level Sales and Profit
# ------------------------------------------------------------
# These values make the customer intelligence analysis
# more useful for Power BI.

customer_summary = df.groupby("Customer ID").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Order_Count=("Order ID", "nunique")
).reset_index()

rfm = rfm.merge(
    customer_summary,
    on="Customer ID",
    how="left"
)

# ------------------------------------------------------------
# BLOCK 10: Create summary tables
# ------------------------------------------------------------

value_summary = rfm.groupby(
    "Customer_Value"
).agg(
    Customers=("Customer ID", "count"),
    Total_Sales=("Total_Sales", "sum"),
    Total_Profit=("Total_Profit", "sum"),
    Average_RFM_Score=("RFM_Score", "mean")
).reset_index()

# ------------------------------------------------------------
# BLOCK 11: Save results to Excel
# ------------------------------------------------------------
# The Excel workbook contains:
#
# 1. Customer RFM details
# 2. Customer-value summary
# 3. RFM score summary

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    rfm.to_excel(
        writer,
        sheet_name="RFM_Customer_Data",
        index=False
    )

    value_summary.to_excel(
        writer,
        sheet_name="Customer_Value_Summary",
        index=False
    )

    pd.DataFrame({
        "Metric": [
            "Total Customers",
            "Average Recency",
            "Average Frequency",
            "Average Monetary",
            "Average RFM Score"
        ],

        "Value": [
            len(rfm),
            rfm["Recency"].mean(),
            rfm["Frequency"].mean(),
            rfm["Monetary"].mean(),
            rfm["RFM_Score"].mean()
        ]
    }).to_excel(
        writer,
        sheet_name="RFM_Summary",
        index=False
    )

# ------------------------------------------------------------
# BLOCK 12: Display results
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("RFM ANALYSIS COMPLETED")
print("=" * 60)

print("\nCustomer Value Distribution:")
print(
    rfm["Customer_Value"]
    .value_counts()
)

print("\nRFM Score Range:")
print(
    rfm["RFM_Score"].min(),
    "to",
    rfm["RFM_Score"].max()
)

print("\nOutput saved to:")
print(output_file)

print("\nTop 10 customers by RFM Score:")
print(
    rfm.sort_values(
        "RFM_Score",
        ascending=False
    )[[
        "Customer ID",
        "Recency",
        "Frequency",
        "Monetary",
        "RFM_Score",
        "Customer_Value"
    ]].head(10)
)

print("\nDone!")